[provider]
cluster = "devnet"
wallet = "./assets/deploy/devnet-keypair.json"
[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
h2coin_vault_share = "BH7f9amUq2cK3EHUNAWQeiuodyNuXwiffjPxjmb2wfye"

[programs.devnet]
h2coin_vault_share = "ALjifiKwvSzKLfpebFZ185b3mLAxroEvxYXCcy9Lzw2B"

[programs.mainnet]
h2coin_vault_share = "D56wAMU3PVRYPD5WiDZ4WpvWmPLhEUyv6RpzzHgjssBN"


[workspace]
members = [
  "programs/h2coin_vault_share"
]

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/localnet_initialize.ts"
