[workspace]
members = [
  "programs/h2coin_vault_share"
]
resolver = "2"


[profile.release]
overflow-checks = true
lto = "fat"

[profile.release.build-override]
opt-level = 3
incremental = false
# codegen-units = 1
